// GENERATED by site/build-pages.mjs from registry/keys/program-keys.json - do not edit.
// The badge worker's pinned program public keys: issuer keys verify
// credentials, status keys verify status lists (separate sets, so a
// stolen issuer key can never clear its own revocation bits). Proofs
// resolve by the fragment id they NAME, so rotated-out keys stay pinned
// here until retired from the registry file. PROVISIONED false (the
// pre-ceremony sentinel) fail-closes every badge to unverified.
export const PROVISIONED = true;
export const PINNED_ISSUER_KEYS = [
  { id: "conformance-issuer-1", publicKeyMultibase: "z6Mksq7RMbuY2H3G92f7DeVE5R4gq12CH7t3RRf6qmmHN9DZ" },
];
export const PINNED_STATUS_KEYS = [
  { id: "conformance-status-1", publicKeyMultibase: "z6Mkj3ayFcQMqvnaQkU4CQd4cuwPTDiMUSkmbM28cNq5kLYp" },
];
